#nombre del flujo completo
name: CI Pipeline

#acciones que ejecutan el archivo:
on:
  pull_request:
  push:
    branches:
      - develop

#los jobs son trabajos a ejecutar:
#Aqui se prueba el test del front como un job
jobs:
  front-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup node (instalar node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar las dependencias
        run: npm install

      - name: Ejecutar validaciones frontend
        run: npm run lint

  front-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup node (instalar node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Instalar las dependencias
        run: npm install

      - name: Construir la aplicación
        run: npm run build

  back-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup Java (instalar java)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Dar permisos al wrapper de Maven
        run: chmod +x mvnw

      - name: Ejecutar pruebas backend
        run: ./mvnw test

  back-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup Java (instalar java)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Dar permisos al wrapper de Maven
        run: chmod +x mvnw

      - name: Construir la aplicación backend
        run: ./mvnw clean package -DskipTests